### ISSUE TITLE
Token Verification Throws an Error when Unauthenticated

### ISSUE THREAD

**Issue by TommyJ1994** [aerogear/aerogear-android-sdk#131]
## Expected Behavior
No errors are thrown.

## Actual Behavior
An error is thrown when the token verification functions are being called when unauthenticated.

## Steps to Reproduce the Problem

  1. Use the SDK when authenticated and check the logs.

```
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String[] java.lang.String.split(java.lang.String)' on a null object reference at org.jose4j.jwx.CompactSerializer.deserialize(CompactSerializer.java:30) at org.jose4j.jwx.JsonWebStructure.fromCompactSerialization(JsonWebStructure.java:77) at org.jose4j.jwt.consumer.JwtConsumer.process(JwtConsumer.java:310) at org.jose4j.jwt.consumer.JwtConsumer.processToClaims(JwtConsumer.java:164)  at org.aerogear.mobile.auth.credentials.OIDCCredentials.verifyClaims(OIDCCredentials.java:90)  at org.aerogear.mobile.auth.AuthService.currentUser(AuthService.java:117)  at com.feedhenry.securenativeandroidtemplate.features.network.presenters.UploadNotesPresenter$ClientStatusCheckerTask.doInBackground(UploadNotesPresenter.java:95)  at com.feedhenry.securenativeandroidtemplate.features.network.presenters.UploadNotesPresenter$ClientStatusCheckerTask.doInBackground(UploadNotesPresenter.java:78)   at android.os.AsyncTask$2.call(AsyncTask.java:333)  at java.util.concurrent.FutureTask.run(FutureTask.java:266)  at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636) at java.lang.Thread.run(Thread.java:764) 
```

## Specifications

  - Core SDK Version: 0.0.1.SNAPSHOT
  - Relevant Service Modules: auth

**Comment by TommyJ1994** [comment]
Implemented in https://github.com/aerogear/aerogear-android-sdk/pull/150
