### ISSUE TITLE
Example app crashes when using local Keycloak

### ISSUE THREAD

**Issue by aidenkeating** [aerogear/aerogear-android-sdk#190]
## Expected Behavior

App should allow me to connect to my Keycloak server if I use that instead of the provided one in the example app.

## Actual Behavior

App crashes when using own Keycloak server instead of provided one in example app.

```
FATAL EXCEPTION: pool-3-thread-1
                                                                           Process: org.aerogear.mobile.example, PID: 4954
                                                                           java.lang.NullPointerException: Attempt to invoke virtual method 'int okhttp3.Response.code()' on a null object reference
                                                                               at org.aerogear.mobile.core.http.OkHttpResponse.getStatus(OkHttpResponse.java:102)
                                                                               at org.aerogear.mobile.auth.credentials.JwksManager.lambda$fetchJwks$0$JwksManager(JwksManager.java:113)
                                                                               at org.aerogear.mobile.auth.credentials.JwksManager$$Lambda$0.run(Unknown Source:26)
                                                                               at org.aerogear.mobile.core.http.OkHttpResponse.runCompletionHandler(OkHttpResponse.java:52)
                                                                               at org.aerogear.mobile.core.http.OkHttpResponse.lambda$new$0$OkHttpResponse(OkHttpResponse.java:40)
                                                                               at org.aerogear.mobile.core.http.OkHttpResponse$$Lambda$0.run(Unknown Source:20)
                                                                               at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
                                                                               at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
                                                                               at java.lang.Thread.run(Thread.java:764)
```

## Steps to Reproduce the Problem

  1. Change the URL of Keycloak in `mobile-services.json` in the example app to a local Keycloak
  2. Try to initiate auth

**Comment by aidenkeating** [comment]
@StephenCoady Are there any steps I'm missing here to reproduce the bug we saw?

**Comment by StephenCoady** [comment]
No I think thats all @aidenkeating. I can take a look at this as a way to get familiar with the app and sdk.

**Comment by ciaranRoche** [comment]
Hey @StephenCoady as a sanity check, can you have a look at the urls. I have seen this error before, but haven't been able to recreate it now. From memory it was a mistake in the url specified in the config file, when `okhttp` could not get a response it threw that weird error and crashed the app. 
If I use the following service config:
```
"services": [
        {
            "id": "keycloak",
            "name": "keycloak",
            "type": "keycloak",
            "url": "https://keycloak-myproject.192.168.37.1.nip.io",
            "config": {
                "auth-server-url": "https://keycloak-myproject.192.168.37.1.nip.io/auth/",
                "realm": "secure-app",
                "resource": "client-app",
                "ssl-required": "external",
                "url": "https://keycloak-myproject.192.168.37.1.nip.io/auth/"
            }
        }
```
I get a failure error, `okHttp` will not accept the request as it is not trusted but it doesn't crash the app.

**Comment by aidenkeating** [comment]
@StephenCoady So the issue was caused by the realm and resource not existing in Keycloak?

The new error you're seeing is probably down to the Keycloak being pointed at using a self-signed cert. I think we still have self-signed certs work to address this planned.

**Comment by ciaranRoche** [comment]
Closing as this issue has been resolved in https://github.com/aerogear/aerogear-android-sdk/pull/192
